---
title: "Sparkline scorecard test"
author: "Paul Bivand"
date: "19 Nov 2015"
output: html_document
---

```{r preparation, echo=FALSE, message=FALSE, warning=FALSE}
library(htmlwidgets)
library(sparkline)
#Employment
a <- round(tail(overall[,6], 25)/10000,1)*10000
a.1 <- format(tail(a,1),big.mark=",")
b <- round(tail(workage[,14], 25),1)
b.1 <- paste0(tail(b,1), "%")
b.2 <- tail(diff(b, lag=12),1)
#Male employment
c <- round(tail(maleallage[,6], 25)/10000,1)*10000
c.1 <- format(tail(c,1),big.mark=",")
d <- round(tail(male_workage[,14], 25),1)
d.1 <- paste0(tail(d,1), "%")
d.2 <- tail(diff(d, lag=12),1)
#Female employment
e <- round(tail(femaleallage[,6], 25)/10000,1)*10000
e.1 <- format(tail(e,1),big.mark=",")
f <- round(tail(female_workage[,14], 25),1)
f.1 <- paste0(tail(f,1), "%")
f.2 <- tail(diff(f, lag=12),1)
#ILO unemployment
g <- round(tail(overall[,8], 25)/10000,1)*10000
g.1 <- format(tail(g,1),big.mark=",")
h <- round(tail(overall[,16], 25),1)
h.1 <- paste0(tail(h,1), "%")
h.2 <- tail(diff(h, lag=12),1)
#Claimant count
i <- tail(claimants[,3], 25)*1000
i.1 <- format(tail(i,1),big.mark=",")
j <- round(tail(claimants[,4], 25),1)
j.1 <- paste0(tail(j,1), "%")
j.2 <- tail(diff(j, lag=12),1)
#Econ inactive
k <- round(tail(workage[,10], 25)/10000,1)*10000
k.1 <- format(tail(k,1),big.mark=",")
l <- round(tail(workage[,18], 25),1)
l.1 <- paste0(tail(l,1), "%")
l.2 <- tail(diff(l, lag=12),1)
#Involunt part-time
m <- round(tail(involunt_emp[,18], 25)/10000,1)*10000
m.1 <- format(tail(m,1),big.mark=",")
n <- round(tail(involunt_emp[,20], 25),1)
n.1 <- paste0(tail(n,1), "%")
n.2 <- tail(diff(n, lag=12),1)
#Workless yp
library(zoo)
library(ggplot2)
ypnfte <- fortify(ypnfte, melt=TRUE)
o <- round(ypnfte[,3]/10000,1)*10000
o.1 <- format(tail(o,1),big.mark=",")
p <- unname(round(rowSums(tail(youth,25)[,14:15])/tail(youth,25)[,2],3)*100)
p.1 <- paste0(tail(p,1), "%")
p.2 <- tail(diff(p, lag=12),1)
#LT youth unem
q <- unname(round(rowSums(tail(unem1824[,c(22,24)],25))/1000)*1000)
q.1 <- format(tail(q,1),big.mark=",")
r <- unname(rowSums(tail(duration_claimants[,c(16,19)],27))*1000)
r<- round(head(r,25)/q,3)*100
r.1 <- paste0(tail(r,1), "%")
r.2 <- tail(diff(r, lag=12),1)
#JSA leavers
s <- tail(claimants_thousands[,3],26)
s.1 <- format(tail(s,1), big.mark=",")
t <- as.numeric(round(leaver.rate,3)*100)
t.1 <- paste0(tail(t,1), "%")
t.2 <- tail(diff(t, lag=12),1)
#JSA new claims
u <- tail(claimants_thousands[,2],26)
u.1 <- format(tail(u,1), big.mark = ",")
v <- as.numeric(tail(round(season_pars[,1],3),25)*100)
v.1 <- paste0(tail(v,1), "%")
v.2 <- tail(diff(v, lag=12),1)
#JSA becoming 12 months
x <- as.numeric(tail(round(seastest_12,3),25)*100)
x.1 <- paste0(tail(x,1),"%")
y <- as.numeric(tail(round(season_pars[,1] - season_pars[,5],3),25)*100)
y.1 <- paste0(tail(y,1), "%")
y.2 <- tail(diff(y, lag=12),1)
#Long term adult unemployment
z <- round(as.numeric(unemployedo)/1000,0)*1000
z.1 <- format(tail(z,1),big.mark=",")
aa <- round(as.numeric(head(old_lt[,2]/old_lt[,1],25)),3)*100
aa.1 <- paste0(tail(aa,1), "%")
aa.2 <- tail(diff(aa, lag=12),1)
#Vacancies
ab <- as.numeric(vacs)
ab.1 <- format(tail(ab,1),big.mark=",")
ac <- as.numeric(head(tail(zooreg(vacancies[,5], start=c(2001,5), frequency=12),26),25))
ac.1 <- tail(ac,1)
ac.2 <- tail(diff(ac, lag=12),1)
#Hours
ad <- round(tail(overall[,6], 25)/10000,1)*10000
ad.1 <- format(tail(ad,1),big.mark=",")
ae <- round(tail(workage[,14], 25),1)
ae.1 <- paste0(tail(ae,1), "%")
ae.2 <- tail(diff(ae, lag=12),1)


```


|  Indicator | Trend (two years) | Latest result | Annual change in rate | Latest result | Trend (two years) |
|------------|-------------------|---------------|-----------------------|---------------|-------------------|
| Employment | `r sparkline(a)`  | `r a.1`       | `r b.2`               | `r b.1`       | `r sparkline(b)`  |
| Male Employment | `r sparkline(c)`  | `r c.1`       | `r d.2`               | `r d.1`       | `r sparkline(d)`  |
| Female Employment | `r sparkline(e)`  | `r e.1`       | `r f.2`               | `r f.1`       | `r sparkline(f)`  |
| ILO unemployment | `r sparkline(g)`  | `r g.1`       | `r h.2`               | `r h.1`       | `r sparkline(h)`  |
| Claimant count (JSA & UC) | `r sparkline(i)`  | `r i.1`       | `r j.2`               | `r j.1`       | `r sparkline(j)`  |
| Economic inactivity (working age)| `r sparkline(k)`  | `r k.1`       | `r l.2`               | `r l.1`       | `r sparkline(l)`  |
| Involuntary part-time working | `r sparkline(m)`  | `r m.1`       | `r n.2`               | `r n.1`       | `r sparkline(n)`  |
| Workless young people (not in FT ED) | `r sparkline(o)`  | `r o.1`       | `r p.2`               | `r p.1`       | `r sparkline(p)`  |
| Long term youth unemployment, % claiming Jobseeker’s Allowance | `r sparkline(q)`  | `r q.1`       | `r r.2`               | `r r.1`       | `r sparkline(r)`  |
| Jobseeker's Allowance leavers | `r sparkline(s)`  | `r s.1`       | `r t.2`               | `r t.1`       | `r sparkline(t)`  |
| Jobseeker’s Allowance flows – new claims and rate of those claiming beyond three months | `r sparkline(u)`  | `r u.1`       | `r v.2`               | `r v.1`       | `r sparkline(v)`  |
| Jobseeker’s Allowance flows – proportion still claiming at 12 months and long term compared to short term | `r sparkline(x)`  | `r x.1`       | `r y.2`               | `r y.1`       | `r sparkline(y)`  |
| Long-term adult unemployment and % of long term adult unemployed claiming Jobseeker’s Allowance | `r sparkline(z)`  | `r z.1`       | `r aa.2`               | `r aa.1`       | `r sparkline(aa)`  |
| Vacancies and vacancies per person unemployed | `r sparkline(ab)`  | `r ab.1`       | `r ac.2`               | `r ac.1`       | `r sparkline(ac)`  |
| Hours worked (total) and average hours worked  | `r sparkline(o)`  | `r o.1`       | `r p.2`               | `r p.1`       | `r sparkline(p)`  |
