library(jsonlite)
library(dplyr)
library(tidyr)
library(xts)
mgrz <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/mgrz/data")
mgrz <- zooreg(as.numeric(mgrz$months$value), start=c(1971,2), frequency = 12)
lf24 <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/lf24/data")
lf24 <- zooreg(as.numeric(lf24$months$value), start=c(1971,2), frequency = 12)
mgsa <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/mgsa/data")
mgsa <- zooreg(as.numeric(mgsa$months$value), start=c(1971,2), frequency = 12)
mgsb <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/mgsb/data")
mgsb <- zooreg(as.numeric(mgsb$months$value), start=c(1971,2), frequency = 12)
mgsv <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/mgsv/data")
mgsv <- zooreg(as.numeric(mgsv$months$value), start=c(1971,2), frequency = 12)
lf25 <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/lf25/data")
lf25 <- zooreg(as.numeric(lf25$months$value), start=c(1971,2), frequency = 12)
mgsc <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/mgsc/data")
mgsc <- zooreg(as.numeric(mgsc$months$value), start=c(1971,2), frequency = 12)
mgsx <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/mgsx/data")
mgsx <- zooreg(as.numeric(mgsx$months$value), start=c(1971,2), frequency = 12)
lf2m <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/economicinactivity/timeseries/lf2m/data")
lf2m <- zooreg(as.numeric(lf2m$months$value), start=c(1971,2), frequency = 12)
lf2s <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/economicinactivity/timeseries/lf2s/data")
lf2s <- zooreg(as.numeric(lf2s$months$value), start=c(1971,2), frequency = 12)
a02 <- merge.zoo(mgrz, lf24, mgsa, mgsv, mgsb, lf25, mgsc, mgsx, lf2m, lf2s)
names(a02) <- c("Employment", "Employment.rate", "Male.employment", "Male.employment.rate", "Female.employment", "Female.employment.rate", "ILO.unemployment", "ILO.unemployment.rate", "Economic.inactivity", "Economic.inactivity.rate")


bcjd <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/timeseries/bcjd/data")
bcjd <- zooreg(as.numeric(bcjd$months$value), start=c(1971,1), frequency = 12)
bcje <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/timeseries/bcje/data")
bcje <- zooreg(as.numeric(bcje$months$value), start=c(1971,1), frequency = 12)
cla01 <- merge.zoo(bcjd, bcje)
names(cla01) <- c("Claimant.count", "Claimant.count.rate")

yccx <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/yccx/data")
yccx <- zooreg(as.numeric(yccx$months$value), start=c(1992,4), frequency = 12)
ycda <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/ycda/data")
ycda <- zooreg(as.numeric(ycda$months$value), start=c(1992,4), frequency = 12)
ybus <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/ybus/data")
ybus <- zooreg(as.numeric(ybus$months$value), start=c(1971,2), frequency = 12)
ybuv <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/ybuv/data")
ybuv <- zooreg(as.numeric(ybuv$months$value), start=c(1992,4), frequency = 12)

agol <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/agol/data")
agol <- zooreg(as.numeric(agol$months$value), start=c(1992,4), frequency = 12)
agpm <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/economicinactivity/timeseries/agpm/data")
agpm <- zooreg(as.numeric(agpm$months$value), start=c(1992,4), frequency = 12)
jn5r <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/jn5r/data")
jn5r <- zooreg(as.numeric(jn5r$months$value), start=c(1992,4), frequency = 12)

ybxv <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/ybxv/data")
ybxv <- zooreg(as.numeric(ybxv$months$value), start=c(1992,4), frequency = 12)
ybxy <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/ybxy/data")
ybxy <- zooreg(as.numeric(ybxy$months$value), start=c(1992,4), frequency = 12)
ybyn <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/ybyn/data")
ybyn <- zooreg(as.numeric(ybyn$months$value), start=c(1992,4), frequency = 12)
ybzc <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/ybzc/data")
ybzc <- zooreg(as.numeric(ybzc$months$value), start=c(1992,4), frequency = 12)

lfs1992 <- merge.zoo(yccx, ycda, ybuv, agol, agpm, jn5r, ybxv, ybxy, ybyn, ybzc)
lfs1992$wypnfte <- agol + agpm
lfs1992$wypnrate <- (agol+agpm)/jn5r
lfs1992$ltyue <- ybxv + ybxy
lfs1992$ltaue <- ybyn + ybzc

ap2y <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/timeseries/ap2y/data")
ap2y <- zooreg(as.numeric(ap2y$months$value), start=c(2001,5), frequency = 12)
jpc5 <- fromJSON("http://www.ons.gov.uk/employmentandlabourmarket/peoplenotinwork/unemployment/timeseries/jpc5/data")
jpc5 <- zooreg(as.numeric(jpc5$months$value), start=c(2001,5), frequency = 12)

vacs2001 <- merge.zoo(ap2y, jpc5)
